version: 2
updates:
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker-compose'
    directory: '/create-agents-template'
    schedule:
      interval: 'weekly'
